import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  flex: {flex: 1},
  containerGroub: {
    flex: 1,
    backgroundColor: 'yellow',
    padding: 10,
  },
  viewCustom: {flexDirection: 'row'},
  customTouchOpacity: {
    backgroundColor: 'blue',
    width: 125,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  textStyle2: {fontSize: 17, color: 'white'},
  customText: {
    marginLeft: 10,
    fontSize: 20,
    color: 'red',
  },
  customVuewTime: {marginTop: 20, flexDirection: 'row'},
  touchableOpa: {
    position: 'absolute',
    right: 10,
    bottom: 10,
    backgroundColor: 'red',
    width: 100,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  viewNew: {
    position: 'absolute',
    right: 10,
    bottom: 60,
    backgroundColor: 'blue',
    width: 100,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  showTime: {
    position: 'absolute',
    left: 10,
    bottom: 0,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    fontSize: 20,
    color: 'blue',
  },
});
